project:
  type: website
  output-dir: docs

website:
  title: Packet Traffic Learning
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO-523-SU25/final-project-garcia-kyle
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true

execute:
  freeze: auto
