{
  "hash": "ee56223c3c534f564826eee36c344db8",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Packet Traffic Learning\"\nsubtitle: \"Proposal\"\nauthor: \n  - name: \"The Anomalists - Joey Garcia, David Kyle\"\n    affiliations:\n      - name: \"College of Information Science, University of Arizona\"\ndescription: \"Project description: Our project aims to develop a predictive model to detect anomalous network behavior using packet-level and statistical features derived from network traffic. With machine learning models, we aim to accurately classify and predict network anomalies, which is essential for intrusion detection, network security monitoring, and incident response automation.\"\nformat:\n  html:\n    code-tools: true\n    code-overflow: wrap\n    code-line-numbers: true\n    embed-resources: true\neditor: visual\ncode-annotations: hover\nexecute:\n  warning: false\njupyter: python3\n---\n\n::: {#load-pkgs .cell message='false' execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport seaborn as sns\nimport matplotlib.pyplot as plt\nfrom scipy import stats # for analysis plan\n```\n:::\n\n\n## Dataset\n\nOur dataset doesn't include column names, we'll add the column names to the in-memory dataframes.\n\n::: {#load-dataset .cell message='false' execution_count=2}\n``` {.python .cell-code}\ndf_train = pd.read_csv('data/KDDTrain.csv')\ndf_test = pd.read_csv('data/KDDTest.csv')\n\n'''\nColumns recieved from kaggle project \nhttps://www.kaggle.com/code/faizankhandeshmukh/intrusion-detection-system\n\n'''\n\n# Define the list of column names based on the NSL-KDD dataset description\ncolumns = [\n    'duration', 'protocol_type', 'service', 'flag', 'src_bytes', 'dst_bytes',\n    'land', 'wrong_fragment', 'urgent', 'hot', 'num_failed_logins',\n    'logged_in', 'num_compromised', 'root_shell', 'su_attempted', 'num_root',\n    'num_file_creations', 'num_shells', 'num_access_files', 'num_outbound_cmds',\n    'is_host_login', 'is_guest_login', 'count', 'srv_count', 'serror_rate',\n    'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',\n    'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count',\n    'dst_host_srv_count', 'dst_host_same_srv_rate', 'dst_host_diff_srv_rate',\n    'dst_host_same_src_port_rate', 'dst_host_srv_diff_host_rate',\n    'dst_host_serror_rate', 'dst_host_srv_serror_rate', 'dst_host_rerror_rate',\n    'dst_host_srv_rerror_rate', 'attack', 'level'\n]\n\n# Assign the column names to the dataframe\ndf_train.columns = columns\ndf_test.columns = columns\n\n\nprint('Shapes (train, test):', df_train.shape, df_test.shape)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nShapes (train, test): (125972, 43) (22543, 43)\n```\n:::\n:::\n\n\nWe are using a training and testing dataset of network intrusion detection from [NSL-KDD from Kaggle](https://www.kaggle.com/datasets/hassan06/nslkdd/data?select=KDDTrain1.jpg). The intrusion detection network traffic training dataset contains **125,972 rows** and **43 columns**, and **22,543 rows** and **43 columns** in the test dataset.\n\nThe `attack` field indicates normal or anomalous (multi-class) observations which allows us to use learning approaches for classifying anomalous network activity. A new binary classification feature, `is_anomalous`, will be added to indicate if the network connection was anomalous or not. This will be the target field for the project.\n\nWe chose this dataset because it provides a rich and realistic representation of network traffic data. The presence of labeled data allows us to train and evaluate supervised models; the diversity and volume of traffic patterns make it well-suited for exploring unsupervised anomaly detection techniques as well. This balance between complexity and feature richness aligns well with our research questions and modeling goals.\n\n## Questions\n\nQ1. Using a supervised learning model such as XGBoost, how accurate can we classify network traffic as normal or anomalous? What features are most influential in driving the model's predictions?\n\nQ2. Can unsupervised learning methods such as K-Means Clustering and Density-based spatial clustering of applications with noise (DBSCAN) detect anomalous network traffic without labeled data? How do they group the traffic network traffic, and how do the results compare to the supervised models?\n\nSummary. In addition to evaluating the performance of supervised and unsupervised models on the task of anomaly detection, we compare the most influential features identified by each approach. This allows us to investigate how different learning paradigms \"perceive\" and prioritize threat indicators (features) within the same dataset.\n\n## Dataset Analysis\n\n### Variables\n\n| Column Name | Data Type | Description |\n|------------------|----------------|--------------------------------------|\n| `duration` | int64 | Length (in seconds) of the connection. |\n| `protocol_type` | object | Protocol used (e.g., tcp, udp, icmp). |\n| `service` | object | Network service on the destination (e.g., http, telnet). |\n| `flag` | object | Status flag of the connection. |\n| `src_bytes` | int64 | Number of data bytes sent from source to destination. |\n| `dst_bytes` | int64 | Number of data bytes sent from destination to source. |\n| `land` | int64 | 1 if connection is from/to the same host/port; 0 otherwise. |\n| `wrong_fragment` | int64 | Number of wrong fragments. |\n| `urgent` | int64 | Number of urgent packets. |\n| `hot` | int64 | Number of \"hot\" indicators. |\n| `num_failed_logins` | int64 | Number of failed login attempts. |\n| `logged_in` | int64 | 1 if successfully logged in; 0 otherwise. |\n| `num_compromised` | int64 | Number of compromised conditions. |\n| `root_shell` | int64 | 1 if root shell is obtained; 0 otherwise. |\n| `su_attempted` | int64 | 1 if \"su root\" command attempted; 0 otherwise. |\n| `num_root` | int64 | Number of \"root\" accesses. |\n| `num_file_creations` | int64 | Number of file creation operations. |\n| `num_shells` | int64 | Number of shell prompts invoked. |\n| `num_access_files` | int64 | Number of accesses to control files. |\n| `num_outbound_cmds` | int64 | Number of outbound commands (always 0 in KDD99). |\n| `is_host_login` | int64 | 1 if login is to a host account; 0 otherwise. |\n| `is_guest_login` | int64 | 1 if login is to a guest account; 0 otherwise. |\n| `count` | int64 | Number of connections to the same host in the past 2 seconds. |\n| `srv_count` | int64 | Number of connections to the same service in the past 2 seconds. |\n| `serror_rate` | float64 | \\% of connections with SYN errors. |\n| `srv_serror_rate` | float64 | \\% of connections to the same service with SYN errors. |\n| `rerror_rate` | float64 | \\% of connections with REJ errors. |\n| `srv_rerror_rate` | float64 | \\% of connections to the same service with REJ errors. |\n| `same_srv_rate` | float64 | \\% of connections to the same service. |\n| `diff_srv_rate` | float64 | \\% of connections to different services. |\n| `srv_diff_host_rate` | float64 | \\% of connections to different hosts on the same service. |\n| `dst_host_count` | int64 | Number of connections to the destination host. |\n| `dst_host_srv_count` | int64 | Number of connections to the destination host and service. |\n| `dst_host_same_srv_rate` | float64 | \\% of connections to the same service on the destination host. |\n| `dst_host_diff_srv_rate` | float64 | \\% of connections to different services on the destination host. |\n| `dst_host_same_src_port_rate` | float64 | \\% of connections from the same source port. |\n| `dst_host_srv_diff_host_rate` | float64 | \\% of connections to the same service from different hosts. |\n| `dst_host_serror_rate` | float64 | \\% of connections with SYN errors to the destination host. |\n| `dst_host_srv_serror_rate` | float64 | \\% of connections with SYN errors to the destination service. |\n| `dst_host_rerror_rate` | float64 | \\% of connections with REJ errors to the destination host. |\n| `dst_host_srv_rerror_rate` | float64 | \\% of connections with REJ errors to the destination service. |\n| `attack` | object | Label indicating the type of attack or \"normal\". |\n| `level` | int64 | Severity or confidence score of the attack (if available). |\n\n### Exploratory Data Analysis\n\nEvaluate training data for any obvious imbalances.\n\n::: {#exploratory-data-analysis .cell execution_count=3}\n``` {.python .cell-code}\nprint(\"Shape:\", df_train.shape)\nprint(\"Missing values:\", df_train.isna().sum().sum())\nprint(\"Duplicates:\", df_train.duplicated().sum())\nprint(\"Unique attack labels:\", df_train['attack'].nunique())\nprint(\"Attack label distribution:\\n\", df_train['attack'].value_counts().head(5))\n\n# Show types and non-null counts\ndf_train.info(verbose=False)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nShape: (125972, 43)\nMissing values: 0\nDuplicates: 0\nUnique attack labels: 23\nAttack label distribution:\n attack\nnormal       67342\nneptune      41214\nsatan         3633\nipsweep       3599\nportsweep     2931\nName: count, dtype: int64\n<class 'pandas.core.frame.DataFrame'>\nRangeIndex: 125972 entries, 0 to 125971\nColumns: 43 entries, duration to level\ndtypes: float64(15), int64(24), object(4)\nmemory usage: 41.3+ MB\n```\n:::\n:::\n\n\nThe brief look at the data is positive. There are plenty of data points and features. Depending on time and model fitting speed, we may decrease our sample size because hyperparameter tuning using GridSearchCV can be computationally intensive. There are no missing values, and the glimpse of the attack column provides insight into why we want to collapse it into a binary column.\n\n### Normal vs Anomalous Traffic\n\nFirst, let's evaluate distribution of normal v. anomalous data.\n\n::: {#cell-class-distribution .cell message='false' execution_count=4}\n\n::: {.cell-output .cell-output-display}\n![](proposal_files/figure-html/class-distribution-output-1.png){#class-distribution width=751 height=463}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nattack\nnormal             67342\nneptune            41214\nsatan               3633\nipsweep             3599\nportsweep           2931\nsmurf               2646\nnmap                1493\nback                 956\nteardrop             892\nwarezclient          890\npod                  201\nguess_passwd          53\nbuffer_overflow       30\nwarezmaster           20\nland                  18\nimap                  11\nrootkit               10\nloadmodule             9\nftp_write              8\nmultihop               7\nphf                    4\nperl                   3\nspy                    2\nName: count, dtype: int64\n```\n:::\n:::\n\n\nThe plot provides an idea of the specific attack types expressesd in the data. The plot communicates why it makes sense to group all non-normal traffic together.\n\nWe feature engineer a new column, `is_anomalous`, we identify 0 as `normal` activity and 1 as `anomalous`.\n\n::: {#feature-engineering .cell execution_count=5}\n``` {.python .cell-code}\n# create binary target column: 1 = attack, 0 = normal\n\ndf_train['is_anomalous'] = df_train['attack'].apply(\n  lambda x: 0 if x == 'normal' else 1)\n```\n:::\n\n\nExamine the new column, `is_anaomalous`, to get an idea of the target frequency.\n\n::: {#countplot-anomalous .cell message='false' execution_count=6}\n\n::: {.cell-output .cell-output-display}\n![](proposal_files/figure-html/countplot-anomalous-output-1.png){#countplot-anomalous-1 width=752 height=463}\n:::\n\n::: {#countplot-anomalous-2 .cell-output .cell-output-display execution_count=24}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Count</th>\n      <th>Percentage</th>\n    </tr>\n    <tr>\n      <th>is_anomalous</th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Normal</th>\n      <td>67342</td>\n      <td>53.46</td>\n    </tr>\n    <tr>\n      <th>Attack</th>\n      <td>58630</td>\n      <td>46.54</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nThe `is_anomalous` classification target shows a near-even class distribution indicating the the dataset is well balanced. There should be no need for resampling or class weighting to correct the set. It appears this dataset will be a good candidate for learning models.\n\n## Analysis plan\n\n### Problem Introduction\n\nThe project is to build and evaluate models capable of detecting anomalous network traffic based on connection-level features from the NSL-KDD dataset. The problem is framed as a binary classification task, where each record is labeled as either normal or anomalous. This has real-world applications in intrusion detection systems and network security monitoring.\n\nThe project will explore both supervised and unsupervised machine learning techniques to assess their effectiveness in identifying attacks from structured network traffic data.\n\n### Feature Engineering Strategy\n\nTo ensure a fair and consistent comparison, we will apply the same feature engineering pipeline to both supervised and unsupervised models. All features will be assigned appropriate column names based on the NSL-KDD documentation. Categorical variables such as `protocol_type`, `service`, and `flag` will be one-hot encoded, and low-variance or non-informative columns will be removed. Numeric features will be standardized using a scaler to normalize their ranges.\n\nFor supervised models, these engineered features will be used alongside the binary target `is_anomalous`. For unsupervised models, the same processed features will be used without labels, allowing the models to explore underlying structure or detect anomalous patterns. This consistent preprocessing ensures that differences in performance and feature relevance can be attributed to the modeling approaches rather than inconsistencies in data preparation.\n\n### Dimensionality Reduction\n\nSince the dataset contains over 40 features, we will apply dimensionality reduction techniques such as Principal Component Analysis (PCA) and Linear Discriminant Analysis (LDA) to aid in visualization, mitigate the curse of dimensionality, and potentially improve model performance. We will evaluate how reduced-dimensional representations affect clustering and classification results and determine whether retaining all features or selecting a subset leads to more interpretable and higher performing models.\n\n### Q1. Supervised Learning\n\nFor the supervised learning portion of the project, we will use the labeled NSL-KDD dataset to train a model that classifies network traffic as normal or anomalous. We will implement XGBoost, a gradient-boosted decision tree algorithm known for its high accuracy, scalability, and built-in mechanisms for handling class imbalance. XGBoost is particularly well-suited for structured tabular data like NSL-KDD and provides useful feature importance measures that support model interpretation.\n\nModel performance will be evaluated using standard classification metrics, including accuracy, precision, recall, F1-score, and ROC AUC. In addition to assessing predictive performance, we will analyze the most influential features identified by the model to better understand what drives the classification of anomalous behavior.\n\n### Q2. Unsupervised Learning\n\nFor the unsupervised learning portion of the project, we will use clustering-based approaches to detect anomalies in network traffic without relying on labeled data. We plan to use K-Means, which partitions data into k-clusters based on distance. Also, we'll use DBSCAN, which identifies clusters of varying shape and isolates outliers as noise. These techniques will be applied to the same feature-engineered data used in the supervised learning tasks.\n\nAfter clustering, we will evaluate how well the resulting groupings align with the true labels using unsupervised performance metrics such as Adjusted Rand Index (ARI) and Fowlkes-Mallows Index (FMI) since we have the labels. We will also examine which features appear most influential in driving cluster separation and anomaly detection, enabling comparison with the supervised model’s learned feature importance.\n\n### Summary Comparison\n\nTo compare the supervised and unsupervised approaches, we will evaluate their effectiveness in detecting anomalous traffic using metrics appropriate to each task. In addition to quantitative performance, we will compare the features deemed most influential by each modeling approach, revealing how different learning paradigms interpret the same network traffic. We will also consider practical factors such as scalability, interpretability, and the requirement for labeled data, to assess the trade-offs between the two strategies.\n\n### Project Timeline\n\n```{=html}\n<style>\n.project-timeline {\n  border-collapse: collapse;\n  width: 100%;\n  font-size: 0.85em;        /* Compact font size */\n  line-height: 1.3;         /* Matches paragraph line spacing closely */\n}\n.project-timeline th, .project-timeline td {\n  border: 1px solid #ccc;\n  padding: 5px 6px;         /* Vertical 5px, horizontal 6px */\n  vertical-align: top;\n}\n.project-timeline th {\n  background-color: #f8f8f8;\n  text-align: left;\n}\n.project-timeline td:first-child {\n  text-align: center;\n  width: 5%;\n}\n.project-timeline th:nth-child(2) { width: 20%; }\n.project-timeline th:nth-child(3) { width: 55%; }\n.project-timeline th:nth-child(4) { width: 20%; }\n</style>\n```\n\n| Week | Task Name | Summary | Team Member(s) |\n|----------|----------|-------------------------------------------|----------|\n| 1 | Dataset exploration | Load the dataset, inspect features, validate schema, sanity-check label balance. | Both |\n| 1 | Define research questions and proposal | Clarify goals for supervised (XGBoost) and unsupervised (K-Means/DBSCAN) anomaly detection. | Both |\n| 2 | EDA & Feature engineering | Explore distributions, correlations, missing data, and outliers; then one-hot encode categoricals, standardize numerics, and remove low-variance/redundant columns to build a reusable pipeline. | Both |\n| 3 | Supervised model development | Train XGBoost to classify traffic as normal vs. anomalous. | David |\n| 3 | Evaluation of supervised models | Use accuracy, precision, recall, F-1, and ROC-AUC to assess performance. | David |\n| 3 | Unsupervised model development | Explore K-Means and DBSCAN to cluster traffic and detect anomalies. | Joey |\n| 4 | Evaluation of unsupervised models | Compare cluster assignments to labels using Adjusted Rand Index; report silhouette where relevant. | Joey |\n| 4 | Comparative analysis | Contrast performance and feature influence across supervised vs. unsupervised approaches. | Both |\n| 5 | Final report & presentation | Compile results, figures, and discussion into final deliverables. | Both |\n\n### File System Organization\n\nThere are no changes to the provided template other than adding the .csv files to the data folder.\n\n",
    "supporting": [
      "proposal_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}